### ISSUE TITLE
[feature request] Translated text only

### ISSUE THREAD

**Issue by NeuroSan** [smark-d/epub-translator#1]
Please add the ability to save the translated version without the original text (to save translated text only).

**Comment by smark-d** [comment]
I will add this feature later this week.

**Comment by smark-d** [comment]
The feature has been added. Please go to the release page and download the latest version.

> Please add the ability to save the translated version without the original text (to save translated text only).

**Comment by NeuroArter** [comment]
> The feature has been added. Please go to the release page and download the latest version.
> 
> > Please add the ability to save the translated version without the original text (to save translated text only).

Thank You. I will try it later today.

**Comment by NeuroArter** [comment]
> The feature has been added.

I checked the same day. Sorry for not answering right away. The point is that nothing has changed with the `-k false` argument. 

Full command is `./epub-translator-linux-amd64 -f book.epub -s en -t ja -e google -k false`

**Comment by smark-d** [comment]
The hyperlinks may won't be broken now.
